# Module 1: Continuing **NumPy**
### Week 7 | May 18, 2026

`NumPy` (Numerical Python) is a powerful open-source Python library used for numerical computing. It provides fast, efficient, and convenient tools for working with large, multi-dimensional arrays and matrices.

This module is three sections, emphasizing NumPy functions, Random module in NumPy, and other mathematrical tools in NumPy.

<h2 style="color:steelblue">Section 1.A: Continuing NumPy</h2>

### 1.A.1 Using Loops with Arrays

- Loops can be used to iterate over one- or multi dimensional arrays
  - 1D array loops through each element one by one
  - An N-dimensional array is a placeholder for however many dimensions the array has
    - First level loops runs against outermost dimension; each nested loop runs against next inner dimension

#### Example:

In [2]:
import numpy as np
arr3d = np.array([[[8,7], [6,5]], [[4,3], [2,1]]])

# loop 1 - iterates over outermost dimension
for x in arr3d:
    print(x)  # output: [[8 7] [6 5]] [[4 3] [2 1]]

# loop 2 - iterates over second dimension
for x in arr3d:
    for y in x:
        print(y)  # output: [8 7] [6 5] [4 3] [2 1]

# loop 3 - iterates down to individual elements
for x in arr3d:
    for y in x:
        for z in y:
            print(z)  # output: 8 7 6 5 4 3 2 1

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]
[8 7]
[6 5]
[4 3]
[2 1]
8
7
6
5
4
3
2
1


### 1.A.2 Joining Arrays with Concatenate()

- Joining puts the contents of two or more arrays into a single array
- In NumPy, arrays are joined on an axis, meaning directions
    - axis=0 (stack on top of each other, add more rows):
    - axis 1 (stack side by side, add more columns):
- The sequence of arrays to be joined is passed to the concatenate() function, with the axis . **If it's not specified, the default axis is 0**
- You can also joing arrays on a new axis using `stack()`

#### Examples:

In [3]:
# Joining two 1D arrays
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6,])
arr_c = np.concatenate((arr_a, arr_b))
print(arr_c)

# Output: [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [4]:
# Joining two 2D arrays on axis 1 (more columns)
arr_d = np.array([[1, 2], [3, 4]])
arr_e = np.array([[5, 6], [7, 8]])
arr_f = np.concatenate((arr_d, arr_e), axis = 1)
print(arr_f)

# Output:  [[1, 2, 5, 6],
#          [3, 4, 7, 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr_g = np.array([1, 2, 3])
arr_h = np.array([4, 5, 6])
arr_i = np.stack((arr_g, arr_h)) # arr_g is row 1, arr_h is row 2. This is joining them
print(arr_i) # since theres no explicit axis =, the default is axis = 0, stacked on top of each other

# Output
# [[1, 2, 3],
# [4, 5, 6]]

arr_j = np.stack((arr_g, arr_h), axis=1) # axis = 1 indicates arrays to stack side by side
print(arr_j)

# Output
# [[1 4]
# [2 5]
# [3 6]]


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 1.A.3. NaN Values

- In NumPy and Pandas, "null" values are called `NaN` (aka "not a number")
- Nan is NOT equal to `None`, and neither are the same as 0 either.

**The difference?**
| | None | NaN | 0 |
|---|---|---|---|
| **Meaning** | Value is set to no value | Value is missing | Value is zero |
| **Data type** | NumPy object dtype | float64 | int/float |
| **Memory** | Takes up more memory | Efficient | Efficient |
| **Vectorized operations** | Changes behavior | Works normally | Works normally |

### 1.A.4 Stacking Helper Functions

NumPy includes helper functions to stack along rows/horiztonal, columns/vertical, or height/depth

#### Examples:

In [6]:
# Base Arrays 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# hstack() – stack horizontally along column axis
arr = np.hstack((arr1, arr2))
print(arr) # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [7]:
# vstack() - stack vertically along row axis
arr = np.vstack((arr1, arr2))
print(arr)      #  [[1, 2, 3],
                 # [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [8]:
# vstack() - stack vertically along row axis
arr = np.vstack((arr1, arr2))
print(arr)      #  [[1, 2, 3],
                 # [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [9]:
# dstack() 0 stack along height/depth
arr = np.dstack((arr1, arr2))
print(arr)    # [[[1, 4],
              # [2, 5],
              # [3, 6]]]         

[[[1 4]
  [2 5]
  [3 6]]]


### 1.A.5 Splitting Arrays

- Split is the reverse of join - splitting breaks on array into multiple
    - `array_split()`: passes arguments of the array too be split, and the number of splits. The result is a list of arrays
    - If the starting array cant be evenly split amoing the new arrays, the results will adjust from the end accordingly.
    - For multidimensional arrays, you can specifyu which axis to split around
    - Helper functions include `hsplit()`, `vsplit()`, `dsplit()`

#### Examples:

In [10]:
# Starting array
arr = np.array([1, 2, 3, 4, 5, 6]) # 1D array

In [11]:
# Splitting into equally sized arrays
newarr1 = np.array_split(arr, 3)
print (newarr1)
# Since theres 6 elements in starting array, it splits evenly in 3 arrays (2 elements for each)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
# Split does not divide evenly into starting array
newarr2 = np.array_split(arr, 4)
print(newarr2)

# Since 6 arrays / 4 arrays is 1 with a remaonder of 2, 2 arrays get an extra element 
# The first arrays with the extra elements first  get 1 element each until it hits the
# 4 array threshold

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [13]:
# Splitting multidimensional arrays by axis 
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
newarr = np.array_split(arr, 2, axis=0)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


### 1.A.6 Using where() to Search and Alter Arrays

- The `where()` function is used to retrieve the indices of elements in an ndarray where a given condition is true

**Syntax**

np.**where(condition**[, x, y]**)**

- A condition must be specifies when using where, but the next two parameters are optional(must use neither of both, not just one):
    - parameter x: specifies a replacement value for first condition
    - parameter y: provides a replacement value where condition was not met; effectively an "else" statement
    -  If only one condition is given as an arugement, it returns a tuple with index location where the value is found. Convert it back to array using array()

In [28]:
# This is what happesn when only one condition is given as an argument 
a = np.array([4,9,4,8,0,6]) 
b = np.where(a < 5) 
print(b) 
# (array([0, 2, 4], dtype=int64),) 
print(np.array(b)) # [[0 2 4]]

# you can also use the .nonzero() function

(array([0, 2, 4]),)
[[0 2 4]]


In [29]:
# The additional parameters can be used to specify a replacement value where the condition is met
c = np.where(a < 5, a, a * .9) 
print(c) 
#  [4. , 8.1, 4. , 7.2, 0. , 5.4] 
# the dot after means it a float. this happened because a * 0.9 produces decimals, so NumPy converts
# the whole array to floats to keep it the same data type, even for the nubmers that didn't change/ meet the condition
d = np.where(a < 5, 'little', a) 
# This essentially says Where the value is less than 5, replace it with 'little'. Where it's not, keep the original number
print(d) 
#  ['little', '9', 'little', '8', 'little', '6']

[4.  8.1 4.  7.2 0.  5.4]
['little' '9' 'little' '8' 'little' '6']


### 1.A.7 Sorting Arrays

- The `sort` function returns a copy of the array as an ordered sequence, meaning in a specific order such as by ascending (smallest to alrgest default).
    - For strings, it means alphabetically. the original array values don't change
- On a multiple dimensional-array, this function will sort each row independently

#### Examples:

In [32]:
# Sorting an array of integers
a = np.array([14, 9, 4, 18, 0, 6])
print(np.sort(a)) 

[ 0  4  6  9 14 18]


In [34]:
# Sort() on a multidimensional array
y=np.array([[[6,2], 
[6,4]],  
[[3,1], 
[9,8]],  
[[9,0], 
[4,2]],  
[[5,4], 
[8,6]]]) 
print(np.sort(y)) 
# It Sorted each row seperately

[[[2 6]
  [4 6]]

 [[1 3]
  [8 9]]

 [[0 9]
  [2 4]]

 [[4 5]
  [6 8]]]


### 1.A.8 Filtering Arrays

- Arrays can be `filtered` based on a Boolean index list / using conditional logic
    - In array filtering, it just means retrieving the values that meet the conditionand ignoring the rest
 

** Although there's not specific function, just use bracked notation with your condition directly with the actual values, or np.where with the index positions. 

#### Examples:

In [36]:
# Filtering using conditional logic
a = np.array([14,9,4,18,0,6]) 
filter_a = [] # Create a blank list to store True/False values
    # loop through every element
for x in a: 
        if x > 10: 
            filter_a.append(True) # meets condition
        else:
            filter_a.append(False) # does't meet condition
            
b = a[filter_a]  # Uses the True/False list to filter, only keeping elements where the position is True
print(b) 

[14 18]


In [38]:
# Shortcut version of exmaple above: But NumPy has a much more efficient option! 
# Boolean indexing
x = a > 10        # variable storing the condition (Boolean mask)
a_over_10 = a[x]  # variable storing the filtered results
print(a_over_10)  # printing the result

# format
# my_condition = a > 10
# my_results = a[my_condition]
# print(my_results)

[14 18]


<h2 style="color:steelblue">Section 1.B: Random Module in NumPy</h2>