# NumPy Arrays — Class Notes

---

## Key Concept
**An array is an object, so it has methods.**

| Array Type | Also Called | Description |
|---|---|---|
| 1D Array | Vector | A linear data structure that stores elements |
| 2D Array | Matrix | Elements arranged in rows and columns; represented as lists of lists |
| 3D Array | — | An array of arrays of arrays; think of it as a cube |

---
## Array Creation

| Function | Syntax | Example | Result |
|---|---|---|---|
| `array()` | `np.array(list)` | `np.array([1,2,3])` | `[1 2 3]` |
| `zeros()` | `np.zeros(shape)` | `np.zeros((2,3))` | 2×3 grid of 0s |
| `ones()` | `np.ones(shape)` | `np.ones((2,2))` | 2×2 grid of 1s |
| `full()` | `np.full(shape, value)` | `np.full((2,2), 7)` | `[7 7; 7 7]` |
| `arange()` | `np.arange(start, stop, step)` | `np.arange(0,10,2)` | `[0 2 4 6 8]` |
| `linspace()` | `np.linspace(start, stop, n)` | `np.linspace(0,1,5)` | `[0 0.25 0.5 0.75 1]` |
| `empty()` | `np.empty(shape)` | — | Uninitialized array |
| `eye()` | `np.eye(n)` | — | Identity matrix |
| `random.rand()` | `np.random.rand(shape)` | — | Random values 0–1 |
| `random.randint()` | `np.random.randint(low, high)` | — | Random integers in range |

In [10]:
import numpy as np

print("=== NumPy Array Creation Functions ===\n")

# 1. array() - create from Python list
a = np.array([1, 2, 3, 4, 5])
print("np.array([1,2,3,4,5])")
print(a, "\n")

# 2. zeros() - array of zeros
b = np.zeros((2, 3))
print("np.zeros((2,3))")
print(b, "\n")

# 3. ones() - array of ones
c = np.ones((2, 2))
print("np.ones((2,2))")
print(c, "\n")

# 4. full() - array filled with a constant value
d = np.full((3, 2), 7)
print("np.full((3,2), 7)")
print(d, "\n")

=== NumPy Array Creation Functions ===

np.array([1,2,3,4,5])
[1 2 3 4 5] 

np.zeros((2,3))
[[0. 0. 0.]
 [0. 0. 0.]] 

np.ones((2,2))
[[1. 1.]
 [1. 1.]] 

np.full((3,2), 7)
[[7 7]
 [7 7]
 [7 7]] 



---
## Array Dimensions — 1D, 2D, 3D

In [11]:
import numpy as np

# 1D Array
arr_1 = np.array([1, 2, 3])
print(arr_1)

# 2D Array
arr_2 = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])
print(arr_2)

# 3D Array
arr_3 = np.array([
    [[1, 2, 3],
     [1, 2, 3],
     [1, 2, 3]],
    [[1, 2, 3],
     [1, 2, 3],
     [1, 2, 3]],
    [[1, 2, 3],
     [1, 2, 3],
     [1, 2, 3]]
])
print(arr_3)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


---
## Array Attributes

| Attribute | Meaning | Example |
|---|---|---|
| `ndim` | Number of dimensions | 1D, 2D, 3D |
| `shape` | Size of each dimension (rows, columns) | `(3, 4)` |
| `size` | Total number of elements | `12` |
| `dtype` | Data type of elements | `int64`, `float64` |
| `itemsize` | Memory size (bytes per element) | `8` |
| `nbytes` | Total memory used | `96` |
| `T` | Transpose (rows ↔ columns) | flipped matrix |
| `real` | Real part (for complex numbers) | real values |
| `imag` | Imaginary part | imaginary values |
| `data` | Buffer storing raw data | memory reference |

In [12]:
import numpy as np

# Basic operations on a 1D array
a = np.array([10, 20, 30, 40])
print(a * 2)      # [20, 40, 60, 80]
print(a.mean())   # 25.0
print(a.dtype)    # int64

# Attributes on a 2D array
a = np.array([[10, 20, 30],
              [40, 50, 60]])

# .shape - dimensions (rows, columns)
print("\nShape of array:", a.shape)
# shows rows and columns

# .ndim - number of dimensions
print("Number of dimensions (ndim):", a.ndim)
# 2

# .dtype - data type of elements
print("Data type (dtype):", a.dtype)

# .size - number of elements
print("Size of array:", a.size)

[20 40 60 80]
25.0
int64

Shape of array: (2, 3)
Number of dimensions (ndim): 2
Data type (dtype): int64
Size of array: 6


---
## Array Manipulation

| Function | Description |
|---|---|
| `np.reshape()` | Reshapes an array without changing its data |
| `np.flatten()` | Flattens a multi-dimensional array into one dimension |
| `np.transpose()` | Transposes the dimensions of an array |
| `np.append()` | Appends values to an array |
| `np.insert()` | Inserts values at specified indices |
| `np.delete()` | Deletes elements from an array |
| `np.concatenate()` | Combines arrays along an axis |
| `np.split()` | Splits an array into multiple sub-arrays |

---
## Statistical Functions

| Function | Description |
|---|---|
| `np.mean()` | Computes the mean of array elements |
| `np.median()` | Finds the median value |
| `np.sum()` | Calculates the sum of elements |
| `np.min()`, `np.max()` | Finds the minimum and maximum values |
| `np.std()`, `np.var()` | Computes standard deviation and variance |
| `np.corrcoef()` | Calculates the correlation coefficient |

---
## Indexing, Slicing, and Filtering

| Syntax | Description |
|---|---|
| `arr[index]` | Accesses elements by index |
| `arr[start:stop:step]` | Slices arrays |
| `arr[arr > value]` | Boolean indexing to filter elements |

---
## Mathematical Operations

| Function | Description |
|---|---|
| `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()` | Element-wise arithmetic operations |
| `np.power()` | Raises elements to a specified power |
| `np.sqrt()` | Computes the square root of each element |
| `np.exp()` | Calculates the exponential of each element |
| `np.log()`, `np.log10()` | Computes natural and base-10 logarithms |
| `np.sin()`, `np.cos()`, `np.tan()` | Trigonometric functions |

---
## File Handling & Utility Functions

| Function | Description |
|---|---|
| `np.save()`, `np.load()` | Save and load arrays in `.npy` format |
| `np.savetxt()`, `np.loadtxt()` | Save and load arrays in text format |
| `np.genfromtxt()` | Loads data from CSV files |
| `np.size()`, `np.shape()`, `np.dtype()` | Inspect array properties |
| `np.copy()` | Creates a deep copy of an array |
| `np.info()` | Displays detailed info about a NumPy function |

---
## Looping Through Arrays

In [14]:
import numpy as np

arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Loops through rows then elements
for row in arr2d:
    print("Row:", row)

# first loop gets rows
# second loop gets elements inside each row
for row in arr2d:
    for value in row:
        print(value)

Row: [1 2 3]
Row: [4 5 6]
1
2
3
4
5
6


In [15]:
import numpy as np

# 3D full traversal — loop tru the elements in 3D
arr3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

# Full traversal
for layer in arr3d:
    for row in layer:
        for value in row:
            print(value)
# This code is doing a full traversal of a 3D NumPy array,
# breaking it down level by level until it reaches individual numbers

1
2
3
4
5
6
7
8


---
## Practice Exercise 1

In [3]:
import numpy as np

# 1. Create a variable named arrA as a two-dimensional array
#    containing (11, 12, 13) and (14, 15, 16) then print arrA
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
# 2x3 table
print(arrA)

[[11 12 13]
 [14 15 16]]


In [9]:
# Looping through the first dimension of arrA and multiplying each element by 2
for x in arrA:
    print(x * 2)
# first dimension means row, so x represents each row and multiplies the entire row by 2

[22 24 26]
[28 30 32]


In [8]:
# 3. Loop through the second dimension of arrA,
#    assign value*2 to a variable named loop_result
for column in arrA:
    for value in column:
        loop_result = value * 2
# second dimension means columns, so the nested loop goes through each individual element
# and assigns value * 2 to loop_result

# 4. Add another line of code to print loop_result
for column in arrA:
    for value in column:
        loop_result = value * 2
        print(loop_result)

22
24
26
28
30
32


---
## Joining / Concatenating Arrays

| Operation | What happens | Result |
|---|---|---|
| `concatenate` | Joins arrays | `[1 2 3 4 5 6]` |
| `+` operator | Element-wise addition | `[5 7 9]` |

***if you use concate operator, values of first array get appended to the other***

***+ operator adds everything in the array with their respective indexes***



### Stacking Helper Functions

| Function | Purpose | Axis | Syntax |
|---|---|---|---|
| `np.concatenate()` | Join along existing axis | flexible (0,1,2...) | `np.concatenate((a,b), axis=...)` |
| `np.stack()` | Join into new dimension | creates new axis | `np.stack((a,b), axis=0)` |
| `np.vstack()` | Vertical / row-wise | axis=0 | `np.vstack((a,b))` |
| `np.hstack()` | Horizontal / column-wise | axis=1 | `np.hstack((a,b))` |
| `np.dstack()` | Depth / 3rd dimension | axis=2 | `np.dstack((a,b))` |
| `np.column_stack()` | Stack as columns | 1D → columns | `np.column_stack((a,b))` |
| `np.row_stack()` | Stack as rows | like vstack | `np.row_stack((a,b))` |

In [22]:
import numpy as np

# 1D concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [23]:
import numpy as np

arrA = np.array([[1, 2], [3, 4]])
arrB = np.array([[5, 6], [7, 8]])

# axis=0 = join vertically (row-wise) → shape becomes (4x2)
result1 = np.concatenate((arrA, arrB), axis=0)
print(result1)

# axis=1 = join horizontally (column-wise) → shape becomes (2x4)
result2 = np.concatenate((arrA, arrB), axis=1)
print(result2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
