# Exercise 5.A NumPy Fundamentals

### Author: Sharleen Guerrero

This notebook covers the fundamentals of NumPy arrays including 
creating 1D, 2D, and 3D arrays, checking data types, transposing, 
and slicing arrays.

## Notes Before I Begin:

**What is NumPy?**
NumPy (Numerical Python) is a library that makes working with numbers and arrays faster and easier than regular Python lists NumPy takes Python lists and converts them into `arrays` (**rows and columns of data**)

**What is an array?**
- 1D array → like a regular list [1, 2, 3]
- 2D array → like a table with rows and columns
- 3D array → like multiple tables stacked on top of each other

**Why use NumPy over regular lists?**
- Much faster for math operations
- Can perform math on entire arrays at once
- Essential for data analysis with pandas and matplotlib

**Key syntax to remember:**
- `np.array([])` → creates an array from a list
- `arr.dtype` → checks the data type of array elements
- `arr.T` → transposes the array (flips rows and columns)
- `arr[row, column]` → slices a specific element
- `np.ones((x,y,z))` → creates an array of all 1s
- `import numpy as np` → always imported as np by convention

## Syntax Breakdown
### Why np.array( [ ?

`np.array()` uses both parentheses and square brackets because two different things are happening:

```python
np.array(   [[1,3,5],[2,4,6]]   )
#        ↑                     ↑
#   function call          close function
#   parentheses ()
#
#              ↑           ↑
#          list argument []
```

- `()` → calling the function (every function call needs parentheses)
- `[]` → the actual data being passed in as a list argument

It's the same pattern as any function call:
- `print("hello")` → () for function, "" for string argument
- `int("5")` → () for function, "" for string argument  
- `np.array([1,2,3])` → () for function, [] for list argument

## What is [1, 3, 5]?

It's a **list** being passed in as an argument to `np.array()`!

For a 2D array, you pass in a **list of lists**:
- The **outer** `[]` → represents the whole table
- The **inner** `[]` → represents each individual row

NumPy then converts that list of lists into a 2D array!

## Does this apply to 3D arrays?

Yes! The same rule applies — `()` for the function call, `[]` for the data.
The only difference is 3D arrays have **three levels of nesting**:
- **Outer** `[]` → the whole collection of tables
- **Middle** `[]` → each individual table
- **Inner** `[]` → each row within a table

```python
np.array([           # outer - collection of tables
    [                # middle - table 1
        [1, 1],      # inner - row 1
        [1, 1]       # inner - row 2
    ],
    [                # middle - table 2
        [1, 1],      # inner - row 1
        [1, 1]       # inner - row 2
    ]
])
```

In [2]:
import numpy as np

## Array Basics

In [14]:
# a) Create the standard Python list for fruits
fruits = ["apple", "banana", "cherry", "date"] 

print(fruits)

['apple', 'banana', 'cherry', 'date']


In [15]:
# b) Converts the Python list fruits into a NumPy array
arr_1 = np.array([fruits])
# Since fruits is one flat list, it's converted to a single, a 1D array (no nesting)
print("=== 1D Array ===")
print(arr_1)
print(arr_1.dtype) # dtype is data type, indicates what type of values are stored in array

# c) Result is <U6, U means Unicode string(text) and 6 means thats the maximum number of 
# characters in the longes string, in this case banana which is 6 characters

=== 1D Array ===
[['apple' 'banana' 'cherry' 'date']]
<U6


In [16]:
# d) Creating a 2D array:
arr_2 = np.array([
    [10,11,12],
    [13,14,15]
])

print(arr_2)
# arr_2 is now like a table with rows and columns. Since python uses zero-based indexing, 
# first row is index 0, next is index 1. It has three columns. Think of it like a table!
# Columns also used zero-based indexing, so first column is index 0, then index 1, then index 2
# To acess a specific element use arr[row, column]:
# arr_2[0, 0]  # → 10  (row 0, col 0)
# arr_2[0, 1]  # → 11  (row 0, col 1)
# arr_2[0, 2]  # → 12  (row 0, col 2)
# arr_2[1, 0]  # → 13  (row 1, col 0)
# arr_2[1, 1]  # → 14  (row 1, col 1)
# arr_2[1, 2]  # → 15  (row 1, col 2)

[[10 11 12]
 [13 14 15]]


In [17]:
# e) Using Transpose
print(arr_2.T)

# Like dtype, transpose is a built in NumPy attribute. It rearranges how the array is 
# displayed, it doesn't permanently change the data inside. It flips rows and columns. 
# Rows become columns, so now the data in row 0 is column 0. Now, arr_2 went from
# 2x3 table to 3x2. Tranpose didn't permanently alter arr_2, it displayed it differently.

[[10 13]
 [11 14]
 [12 15]]


In [18]:
# f) Creating a 2D array named arr_3:
arr_3 = np.array([
    [1,3,5],
    [2,4,6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [20]:
# g) Create a variable named arr_4 as a one-dimensional array containing two values: 
# using slicing notation, the element of arr_3 at index position 0, 2 and the element 
# of arr_3 at index position 1, 1. 
# Element means a single value from the array

# index position 0,2 means row 0, column 2 which is 5
# index position 1,1 means row 1, column 1 which is 4
# arr_3[row, column] is the slicing notation to grab a specific value from the table
# you can create new arrays from existing arrays by calling specific elements from them

arr_4 = np.array([
    arr_3[0, 2],   # grabs value at row 0, column 2
    arr_3[1, 1]    # grabs value at row 1, column 1
])
print(arr_4)

# How is this useful?
# In real data analysis you might have a large table of data and only need
# specific values from it - instead of recreating the data, you can just
# reference the existing array and pull out exactly what you need!
# This avoids duplicating data and keeps your code clean and efficient

[5 4]


In [22]:
# h) Creating a 3D array 
# A 3D array with all 1's and two values in each dimension means:
# 2 tables
# 2 rows in each table
# 2 columns in each row

arr_5 = np.array([
    [[1, 1],   # table 1, row 1
     [1, 1]],  # table 1, row 2
    [[1, 1],   # table 2, row 1
     [1, 1]]   # table 2, row 2
])

print(arr_5)

# 2nd Method
# arr_5 = np.ones((2, 2, 2))
# .ones attribute creates an array consisting of only 1s
# (2, 2, 2) tells the shape, two tables, 2 rows, 2 columns

## What is a Table of 1's Useful For?

A table of 1's created with `np.ones()` is useful in several real world scenarios:

**1. Placeholder/Template**
Create an empty structure to fill in with real data later, like a blank spreadsheet template — you need the structure before the real data!

**2. Math Operations**
Multiplying by 1 doesn't change values, useful for initializing calculations:
`np.ones((3,3)) * 9.99` creates a price table all set to 9.99

**3. Masking**
In data analysis, arrays of 1's and 0's are used to filter data:
- 1 = include this value
- 0 = exclude this value

**4. Neural Networks / Machine Learn