# Exercise 1.A NumPy: Manipulating Arrays

In [25]:
import numpy as np

## Looping Through Arrays

In [26]:
# Creating 2D array
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [27]:
# Looping through the first dimension of arrA and multiplying each element by 2
for row in arrA:
    print(row * 2)
# first dimension means row, so x represents each entire row
# multiplying x by 2 multiplies the whole row at once, returning an array per row

[22 24 26]
[28 30 32]


In [28]:
# Looping through the second dimension of arrA and assigning value*2 to a variable named loop_result
for row in arrA:
    for value in row:
        loop_result = value * 2
        print(loop_result)
# the nested loop goes through each individual element one at a time
# value holds one number at a time, so loop_result returns individual numbers not arrays

22
24
26
28
30
32


**Describe the difference between the results for first loop and the second loop**:

The first loop treats each row as a whole and multiplies the entire row by 2 at once, returning arrays. The second loop has a nested loop that goes deeper into the elements of each row. So, for every row in the array, and every element (value) in that row, the second loop stores the value multiplied by 2 in loop_result and prints it. Since it is going through each element one at a time, it returns individual numbers instead of arrays like the first loop does.


In [29]:
for row in arrA:
    for value in row:
        loop_result = row * 2
print(loop_result)
# For every row in the array, and for every value in that row, it multiplies the whole row by 2 at once
# even though the nested loop visits each element, loop_result is assigned the entire row each time
# since loop_result keeps getting overwritten every iteration, only the last row's result is printed after the loop finishes

[28 30 32]


## Joining and Stacking Arrays

In [30]:
# Concatenating arrA on the default axis
print(arrA)
print()
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(f"Joined Array:\n {joined_array_1}")
# Here I am joining arrA onto itself, so it appends its own values a second time to the array
# Concatenating on axis=0 stacks the arrays vertically (up/down), so arrA appends below itself
# axis=0 

[[11 12 13]
 [14 15 16]]

Joined Array:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [31]:
# Concatenating aarA on the axis=1
# This is the horizontal axis, so it moves left to right across columns, so it adds more columns
print(arrA)
print()
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(f"Joined array 2:\n {joined_array_2}")
# so the array gets stacked next to the original

[[11 12 13]
 [14 15 16]]

Joined array 2:
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [32]:
# Stacking joined arrays on the default axis
# This is the vertical axis, so it moves up and down, so it adds more rows
# Joined array 1's values will stack under joined itself
print(f"Joined array 1:\n {joined_array_1}")
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1), axis=0)
print(f"\nStacked array 1:\n {stacked_array_1}")

Joined array 1:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Stacked array 1:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [36]:
# Stacking joined arrays on the default axis
# This is the vertical axis, so it moves up and down, so it should add more rows
# Joined array 2 will stack under joined array 1, because it is the second parameter
print(f"Joined array 1:\n {joined_array_1}")
print(f"\nJoined array 2:\n {joined_array_2}")
stacked_array_2 = np.concatenate((joined_array_1, joined_array_2), axis=0)
print(f"Stacked array 2:\n{stacked_array_2}")

# The error message is saying since joined array 1 jas 4 rows and 3 columns while 
# joined array 2 has 2 rows and 6 columns, it can't stack them. When stacking vertically,
# both arrays need to have the same number of columns so they can line up. Similarly, if
# I tried to stack them horizontally, it wouldn't work either because they don't have the
# same number of rows.

Joined array 1:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Joined array 2:
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

In [40]:
# Using stacking helper functions to stack arrA onto itself
print(f"Original array:\n{arrA}")

# hstack() - stacks horizontally, so axis = 1
stack_1 = np.hstack((arrA, arrA))
print(f"\nDemonstrating hstack():\n {stack_1}")
# this function adds more columns

# vstack() - stacks vertically, so axis = 0
stack_2 = np.vstack((arrA, arrA))
print(f"\nDemonstrating vstack():\n {stack_2}")
# this function adds more rows

#dstack() - stakcks into third dimensions, so axis = 2
stack_3 = np.dstack((arrA, arrA))
print(f"\nDemonstrating dstack():\n {stack_3}")
#adds a third dimension, pairing each corresponding element from both arrays together 
# along a new depth axis

Original array:
[[11 12 13]
 [14 15 16]]

Demonstrating hstack():
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Demonstrating vstack():
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Demonstrating dstack():
 [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [45]:
# Splitting array into 2 using .split()
print(f"Joined array 1:\n{joined_array_1}")

splitsky = np.split(joined_array_1, 2)
print(f"\nArray split into 2:\n{splitsky}")
# Two arrays
# Each array is 2 dimensiona;, 2 rows and 3 columns

Joined array 1:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Array split into 2:
[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [56]:
# Splitting joined_array_1 into 3 equal parts
print(f"Joined array 1:\n{joined_array_1}")

spliterino = np.split(joined_array_1, 3)
print(f"\nArray split into 3:\n{spliterino}")
# Result: ValueError because array split does not result in an equal division
# np.split() requires the array to be divided equally — joined_array_1 has 4 rows
# which cannot be split evenly into 3 parts
# Use np.array_split() instead if unequal splits are needed
# np.array_split() handles the remainder by giving the extra row to the first array

Joined array 1:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


ValueError: array split does not result in an equal division

## Searching and Replacing Array

In [47]:
# Using np.where() to find even numbers in arrA
# % is the modulo operator — it returns the remainder after division
# % 2 == 0 means "no remainder when divided by 2" which means the number is even
# If condition is met, return the value from arrA; otherwise return 'odd'
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [48]:
# Creating 2D array arrB
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

# np.sort() sorts each row in ascending order by default
arrB_sorted = np.sort(arrB)
print(f"Sorted arrB:\n{arrB_sorted}")

Sorted arrB:
[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [49]:
# Filtering arrB for values less than 7 using boolean masking
print(f"Original arrB:\n{arrB}")

# z is a True/False array — True where values are less than 7
z = arrB < 7
# arrB[z] returns only the values where z is True, flattened into 1D
arrC = arrB[z]
print(f"\nValues less than 7:\n{arrC}")

Original arrB:
[[ 7  6]
 [13  5]
 [ 7  3]]

Values less than 7:
[6 5 3]


In [50]:
# Filtering arrB for values greater than or equal to 7
# y is a True/False array — True where values are >= 7
y = arrB >= 7
arrD = arrB[y]
print(f"Values greater than or equal to 7:\n{arrD}")

Values greater than or equal to 7:
[ 7 13  7]
