# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [5]:
# Creating a variable named r_1 that contains a random set of integers between 1 and 20
# with a size of 2 elements
r_1 = np.random.randint(1, 21, size=(2))
print(r_1)
# I need random.randint because the random module for arrays is withing numpy, not the same
# 1 and 21 are the low and high parameters — low is inclusive, high is exclusive
# so to truly include 20 in the range, high must be set to 21
# size=(2) says how many random integers to generate

[ 8 10]


In [8]:
# Creating a variable named r_2 that contains a random set of integers between 1 and 20 
# with a size of 1 row, 2 columns
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)
# size=(1, 2) are parameters used to specify number of elements by row and column
# Double brackets, so it is a 2D array with 1 row and 2 columns

[[7 6]]


In [9]:
# Creating a variable named r_3 that contains a random set of floats between 0 and 1 
# with a size of 2 rows, 1 columns. 
# rand() generates a random float between 0 and 1
# Doesn't accept start/stop parameters or use size=() label
# the array size is specified directly (number or rows, number of columns)
r_3 = np.random.rand(2, 1)
print(r_3)
# 2D array

[[0.97422798]
 [0.33094124]]


In [10]:
# Creating a variable named r_4 that contains a random set of integers between 20 
# and 100 with a size of 4 rows, 5 columns. 
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[67 34 34 70 84]
 [94 71 96 46 37]
 [55 87 73 83 48]
 [57 60 45 57 27]]


In [13]:
# Create a variable named r_5 that contains a random set of floats between 0 and 1 
# with a size of 4 rows, 5 columns.
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.89931529 0.55028474 0.67953487 0.36949215 0.95630621]
 [0.8351092  0.08705225 0.60056092 0.28267042 0.12690585]
 [0.65400608 0.84164933 0.428656   0.8458336  0.95917986]
 [0.49575385 0.52687325 0.21574355 0.9611856  0.03703307]]


## Generating Random Choices from an Array

In [14]:
# Creating a variable named students and assigning it a 1D array containing the names of
# 12 of my classmates
students = np.array(["Marenza", "Cris", "ShaRya", "Vesna", "Leon", "Kasaiah", "Demy", "Dania", "Lily", "Jordan", "Patrick", "Malaika"])

In [19]:
# Creating a variable named call_on to use it to choose one random selection from students
call_on = np.random.choice(students)
print(call_on)
# np.random.choice() requires the array to be passed directly as a parameter
# wrapping it in extra brackets creates a 2D array which breaks it
# np.random.choice() only works with 1D arrays — for 2D arrays you would need to flatten first

Jordan


In [24]:
# Creating a variable named breakout_groups to randomize sampling from students that is 
# 3 rows and 4 columns
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# you can generate samples from a 1D array by specifying parameters for rows and columns

# This would be an ineffective way to create breakout rooms because the method automatically
# defaults samples with replacement, so when it picks a student, it goes back into the pool
# so it can possibly be picked again. As you can see, Patrick appears twice, which is
# unideal for assigning breakout rooms since he cannot be in two breakout rooms at once.
# to avoid this I'd have to add replace=False as a parameter so it can randomly sample
# unique values each time.

[['Vesna' 'Patrick' 'Patrick' 'Dania']
 ['Jordan' 'Jordan' 'Leon' 'Marenza']
 ['Dania' 'ShaRya' 'Vesna' 'Demy']]


In [28]:
# Creating a variable call_on_weighted to make five random selections from students, but
# assigning probability values that will determine how likely each student is to be 
# selected. One student should have a zero likelihood of being called on, at least one 
# should have a 30% likelihood of being called on
# probability can be specified with parameter p=[]
# must be a float between 0 and 1, and all probabilities across every element must add up to 1.0
call_on_weighted = np.random.choice(students, p=[.3, 0, .05, .2, .05, .1, .1, 0, .1, 0, .1, 0], size=(5))
print(call_on_weighted)
# size=5 is the paramter for the amount of random selections I want

['ShaRya' 'Marenza' 'Lily' 'Demy' 'Lily']


## Generating a Normal Distribution

In [29]:
# Creating a variable named bell_curve and assigning it to a random distribution for which
# the mean(peak of curve) is 10, standard deviation is 5, and the size of the returned array
# is 4 rows by 5 columns
# normal() method generates data distribution using parameters loc (mean), scale (standard
# deviation), size (shape of the returned array in rows and columns)
bell_curve = np.random.normal(loc = 10, scale=5, size=(4, 5))
print(bell_curve)

[[10.30599407 15.75115211 14.80521557 14.83083322 11.36725123]
 [16.68383189  2.74492573  5.93068068  4.1084121   9.3671332 ]
 [16.42975029  9.02635373  7.99087139 19.30491156 -3.35295932]
 [ 8.30053572 13.50255908 11.42136454 16.42678312  2.9524825 ]]
