# Exercise 1.C Performing Operations on Arrays

In [1]:
import numpy as np

## Sample Arrays

In [4]:
# Creating five variables contatining random sample arrays to work with from Exercise 1B

# Generates a 1D array with random values from 1 to 20, 2 elements
r_1 = np.random.randint(1, 21, size=(2))

# Generates a 2D array with random values from 1 to 20, 1 row and 2 columns
r_2 = np.random.randint(1, 21, size=(1, 2))

# Generates a 2D array with random floats 0 to 1, 2 rows and 1 column
r_3 = np.random.rand(2, 1)

# Generates a 2D array with random values from 20 to 100, 4 rows and 5 columns
r_4 = np.random.randint(20, 101, size=(4, 5))

# Generates a 2D array with random floats 0 to 1, 4 rows and 5 columns 
r_5 = np.random.rand(4, 5)

# Printing the sample arrays
print(f"r_1:\n{r_1}")
print(f"\nr_2:\n{r_2}")
print(f"\nr_3:\n{r_3}")
print(f"\nr_4:\n{r_4}")
print(f"\nr_5:\n{r_5}")

r_1:
[15  7]

r_2:
[[5 4]]

r_3:
[[0.05856853]
 [0.80577374]]

r_4:
[[74 84 94 96 56]
 [92 55 47 92 66]
 [60 69 80 29 46]
 [20 65 24 42 46]]

r_5:
[[0.05264433 0.88858026 0.94397857 0.34759003 0.10531212]
 [0.53379219 0.8281948  0.78657103 0.12036323 0.4494631 ]
 [0.97272266 0.9708333  0.83133677 0.02506765 0.68696686]
 [0.89323275 0.08118887 0.47461246 0.64123336 0.18312309]]


## Permutations

In [5]:
# Printing the current value of r_4
print(f"Current r_4:\n{r_4}")

Current r_4:
[[74 84 94 96 56]
 [92 55 47 92 66]
 [60 69 80 29 46]
 [20 65 24 42 46]]


In [8]:
# Using np.random.shuffle to shuffle the values in r_4
# Permutation is a different arrangement/order of the same set of values. The more values 
# in a set, the more permutations
# the function permanently reorders the original array in place so the original order is gone
np.random.shuffle(r_4)
print(f"Shuffled r_4:\n{r_4}")

Shuffled r_4:
[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


#### **How were the elements of the array shuffled?**

The elements of the array were shuffled by row; the order of the rows changed but the values inside the rows stayed in their original order.

In [10]:
# Assigning the value of a random permutation to r_4 using np.random.permutation to new_shuffle
# permutation() returns a new array with the elements in a new random order
new_shuffle = np.random.permutation(r_4)
print(f"new_shuffle:\n{new_shuffle}")
print(f"\nr_4:\n{r_4}") # printing the original r_4 because permutation leaves the 
                        # original untouched

new_shuffle:
[[20 65 24 42 46]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [74 84 94 96 56]]

r_4:
[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


#### **When would you use shuffle versus permutation?**

I would use shuffle when I want to modify the original array. I would use permutation when I want a shuffled copy of the array but keep the original untouched.

## Mathematical Operations

In [19]:
# Printing the shape of r_1 and r_2 using .shape attribute. Using the add function and
# printing the shape of the result
print("r_1:\n", r_1)
print("r_1 shape:\n", r_1.shape)

print("\nr_2:\n", r_2)
print("r_2 shape:\n", r_2.shape)

print("\nThe result of adding r_1 and r_2:\n", np.add(r_1, r_2))
print("\nShape of the Result:\n", (np.add(r_1, r_2)).shape)
# np.add calculates the sum of the first array values and second array values
# shape gives the size of each dimension, rows and columns

# Broadcasting: numpy automatically adjusts arrays of different shapes to work together
# r_1 is 1D with shape (2,) and r_2 is 2D with shape (1, 2)
# numpy stretches r_1 to match r_2's shape so addition happens element by element
# the result takes the shape of the larger array — (1, 2)

r_1:
 [15  7]
r_1 shape:
 (2,)

r_2:
 [[5 4]]
r_2 shape:
 (1, 2)

The result of adding r_1 and r_2:
 [[20 11]]

Shape of the Result:
 (1, 2)


In [20]:
# Printing the shape of r_1 and r_3 using .shape attribute. Using the add function and
# printing the shape of the result

print("r_1:\n", r_1)
print("r_1 shape:\n", r_1.shape)

print("\nr_3:\n", r_3)
print("r_3 shape:\n", r_3.shape)

print("\nThe result of adding r_1 and r_3:\n", np.add(r_1, r_3))
print("\nShape of the Result:\n", (np.add(r_1, r_3)).shape)
# Broadcasting stretches both arrays to match each other's dimensions
# r_1 shape (2,) stretches vertically to match r_3's 2 rows
# r_3 shape (2, 1) stretches horizontally to match r_1's 2 columns
# each float from r_3 gets added to every element in r_1
# the result takes the largest dimension from each array, giving shape (2, 2)
# neither array is actually modified in memory — numpy just treats them as the larger shape

r_1:
 [15  7]
r_1 shape:
 (2,)

r_3:
 [[0.05856853]
 [0.80577374]]
r_3 shape:
 (2, 1)

The result of adding r_1 and r_3:
 [[15.05856853  7.05856853]
 [15.80577374  7.80577374]]

Shape of the Result:
 (2, 2)


In [21]:
# Printing the shape of r_2 and r_4 using .shape attribute. Using the add function and
# printing the shape of the result

print("r_2:\n", r_2)
print("r_2 shape:\n", r_2.shape)

print("\nr_4:\n", r_4)
print("r_4 shape:\n", r_4.shape)

print("\nThe result of adding r_2 and r_4:\n", np.add(r_2, r_4))
print("\nShape of the Result:\n", (np.add(r_2, r_4)).shape)

r_2:
 [[5 4]]
r_2 shape:
 (1, 2)

r_4:
 [[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]
r_4 shape:
 (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

Adding r_2 and r_4 produces a ValueError: 'operands could not be broadcast together with shapes (1,2) (4,5)'. This means their column dimensions are incompatible; r_2 has 2 columns and r_4 has 5 columns. For broadcasting to work, dimensions must either be equal or one of them must be 1 so numpy can stretch it. Since 2 ≠ 5 and neither is 1, numpy cannot broadcast them together. If r_2 had 1 column or 5 columns, it would have worked. 1 is the exception because it's the only value that can be stretched across any number of columns, similar to how 1 times any number always equals that number.

In [28]:
# Test 1
print(r_1)
print()
print(r_4)
np.add(r_1, r_4)

[15  7]

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [29]:
# Test 2
print(r_3)
print()
print(r_4)
np.add(r_3, r_4)

[[0.05856853]
 [0.80577374]]

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

#### **My Findings:**

Test 1 and Test 2 produced a value error because the operands or arrays could not be broadcast or stretched because they have incompatible dimensions. In test 1, r_1 and r_4 couldn't be broadcast together because they have differing amount of columns. If r_1 had one column it would have worked. In r_3, r_4, it didn't work because although r_3 has 1 column, it only has 2 rows that couldn't be stretched to match r_4's 4 rows. The general rule is that broadcasting requires ALL dimensions to be compatible and a dimension is compatible if both values are equal OR one of them is 1. Both the row AND column dimensions must pass the compatibility check — if even one dimension fails, the entire broadcasting operation fails.

In [43]:
print(r_4)
print()
print(np.add(np.array([1]), r_4))

# Adds every individual element in array by 1

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [38]:
print(r_4)
print()
print(np.add(np.array([[1]]), r_4))\
# Also adds every individual element in the array by 1

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [41]:
print(r_4)
print()
print(np.add(np.array([1,1,1,1,1]), r_4))
# np.array([1,1,1,1,1]) is a 1D array with 5 elements matching r_4's 5 columns
# since the column dimension matches, numpy can broadcast it across all 4 rows of r_4
# adding 1 to every element in r_4

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [40]:
print(r_4)
print()
print(np.add(np.array([[1], [1]]), r_4))
# This will not work since the array has 2 columns, it cannot stretch to be compatible 
# with r_4's 4 columns.

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]



ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

#### **How does broadcasting work?:**

Broadcasting works by stretching the dimensions of smaller arrays to match the dimensions of the larger array so the add function can be applied. With the add function, individual elements get added to each other element by element. The shape of the resulting array is determined by the largest dimension of both arrays. For broadcasting to work, every dimension must either be equal between both arrays or one of them must be 1. Both rows AND columns are checked separately — if even one dimension fails the check, the entire operation fails. For example, (2,1) cannot broadcast with (4,5) because even though the 1 column can stretch to 5, the 2 rows cannot stretch to match 4. 

The way I think of it is .add() checks every dimension individually. Rows amnd columns must match, or one has to be equal to 1. If either test for rows and columns fail, the .add() function won't work.  

## Rounding