# Exercise 1.C Performing Operations on Arrays

In [3]:
import numpy as np

## Sample Arrays

In [4]:
# Creating five variables contatining random sample arrays to work with from Exercise 1B

# Generates a 1D array with random values from 1 to 20, 2 elements
r_1 = np.random.randint(1, 21, size=(2))

# Generates a 2D array with random values from 1 to 20, 1 row and 2 columns
r_2 = np.random.randint(1, 21, size=(1, 2))

# Generates a 2D array with random floats 0 to 1, 2 rows and 1 column
r_3 = np.random.rand(2, 1)

# Generates a 2D array with random values from 20 to 100, 4 rows and 5 columns
r_4 = np.random.randint(20, 101, size=(4, 5))

# Generates a 2D array with random floats 0 to 1, 4 rows and 5 columns 
r_5 = np.random.rand(4, 5)

# Printing the sample arrays
print(f"r_1:\n{r_1}")
print(f"\nr_2:\n{r_2}")
print(f"\nr_3:\n{r_3}")
print(f"\nr_4:\n{r_4}")
print(f"\nr_5:\n{r_5}")

r_1:
[3 7]

r_2:
[[17  8]]

r_3:
[[0.30490094]
 [0.42133932]]

r_4:
[[47 54 79 57 91]
 [90 60 66 95 82]
 [57 99 39 22 56]
 [43 27 50 89 57]]

r_5:
[[0.19825132 0.16435236 0.49587721 0.46748983 0.27743991]
 [0.59860162 0.53941494 0.58345313 0.52666265 0.26224233]
 [0.77346637 0.87039316 0.67636182 0.49374469 0.05244341]
 [0.068942   0.87133963 0.9984973  0.01783206 0.47696543]]


## Permutations

In [5]:
# Printing the current value of r_4
print(f"Current r_4:\n{r_4}")

Current r_4:
[[74 84 94 96 56]
 [92 55 47 92 66]
 [60 69 80 29 46]
 [20 65 24 42 46]]


In [8]:
# Using np.random.shuffle to shuffle the values in r_4
# Permutation is a different arrangement/order of the same set of values. The more values 
# in a set, the more permutations
# the function permanently reorders the original array in place so the original order is gone
np.random.shuffle(r_4)
print(f"Shuffled r_4:\n{r_4}")

Shuffled r_4:
[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


#### **How were the elements of the array shuffled?**

The elements of the array were shuffled by row; the order of the rows changed but the values inside the rows stayed in their original order.

In [10]:
# Assigning the value of a random permutation to r_4 using np.random.permutation to new_shuffle
# permutation() returns a new array with the elements in a new random order
new_shuffle = np.random.permutation(r_4)
print(f"new_shuffle:\n{new_shuffle}")
print(f"\nr_4:\n{r_4}") # printing the original r_4 because permutation leaves the 
                        # original untouched

new_shuffle:
[[20 65 24 42 46]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [74 84 94 96 56]]

r_4:
[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


#### **When would you use shuffle versus permutation?**

I would use shuffle when I want to modify the original array. I would use permutation when I want a shuffled copy of the array but keep the original untouched.

## Mathematical Operations

In [19]:
# Printing the shape of r_1 and r_2 using .shape attribute. Using the add function and
# printing the shape of the result
print("r_1:\n", r_1)
print("r_1 shape:\n", r_1.shape)

print("\nr_2:\n", r_2)
print("r_2 shape:\n", r_2.shape)

print("\nThe result of adding r_1 and r_2:\n", np.add(r_1, r_2))
print("\nShape of the Result:\n", (np.add(r_1, r_2)).shape)
# np.add calculates the sum of the first array values and second array values
# shape gives the size of each dimension, rows and columns

# Broadcasting: numpy automatically adjusts arrays of different shapes to work together
# r_1 is 1D with shape (2,) and r_2 is 2D with shape (1, 2)
# numpy stretches r_1 to match r_2's shape so addition happens element by element
# the result takes the shape of the larger array — (1, 2)

r_1:
 [15  7]
r_1 shape:
 (2,)

r_2:
 [[5 4]]
r_2 shape:
 (1, 2)

The result of adding r_1 and r_2:
 [[20 11]]

Shape of the Result:
 (1, 2)


In [20]:
# Printing the shape of r_1 and r_3 using .shape attribute. Using the add function and
# printing the shape of the result

print("r_1:\n", r_1)
print("r_1 shape:\n", r_1.shape)

print("\nr_3:\n", r_3)
print("r_3 shape:\n", r_3.shape)

print("\nThe result of adding r_1 and r_3:\n", np.add(r_1, r_3))
print("\nShape of the Result:\n", (np.add(r_1, r_3)).shape)
# Broadcasting stretches both arrays to match each other's dimensions
# r_1 shape (2,) stretches vertically to match r_3's 2 rows
# r_3 shape (2, 1) stretches horizontally to match r_1's 2 columns
# each float from r_3 gets added to every element in r_1
# the result takes the largest dimension from each array, giving shape (2, 2)
# neither array is actually modified in memory — numpy just treats them as the larger shape

r_1:
 [15  7]
r_1 shape:
 (2,)

r_3:
 [[0.05856853]
 [0.80577374]]
r_3 shape:
 (2, 1)

The result of adding r_1 and r_3:
 [[15.05856853  7.05856853]
 [15.80577374  7.80577374]]

Shape of the Result:
 (2, 2)


In [21]:
# Printing the shape of r_2 and r_4 using .shape attribute. Using the add function and
# printing the shape of the result

print("r_2:\n", r_2)
print("r_2 shape:\n", r_2.shape)

print("\nr_4:\n", r_4)
print("r_4 shape:\n", r_4.shape)

print("\nThe result of adding r_2 and r_4:\n", np.add(r_2, r_4))
print("\nShape of the Result:\n", (np.add(r_2, r_4)).shape)

r_2:
 [[5 4]]
r_2 shape:
 (1, 2)

r_4:
 [[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]
r_4 shape:
 (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

Adding r_2 and r_4 produces a ValueError: 'operands could not be broadcast together with shapes (1,2) (4,5)'. This means their column dimensions are incompatible; r_2 has 2 columns and r_4 has 5 columns. For broadcasting to work, dimensions must either be equal or one of them must be 1 so numpy can stretch it. Since 2 ≠ 5 and neither is 1, numpy cannot broadcast them together. If r_2 had 1 column or 5 columns, it would have worked. 1 is the exception because it's the only value that can be stretched across any number of columns, similar to how 1 times any number always equals that number.

In [28]:
# Test 1
print(r_1)
print()
print(r_4)
np.add(r_1, r_4)

[15  7]

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [29]:
# Test 2
print(r_3)
print()
print(r_4)
np.add(r_3, r_4)

[[0.05856853]
 [0.80577374]]

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

#### **My Findings:**

Test 1 and Test 2 produced a value error because the operands or arrays could not be broadcast or stretched because they have incompatible dimensions. In test 1, r_1 and r_4 couldn't be broadcast together because they have differing amount of columns. If r_1 had one column it would have worked. In r_3, r_4, it didn't work because although r_3 has 1 column, it only has 2 rows that couldn't be stretched to match r_4's 4 rows. The general rule is that broadcasting requires ALL dimensions to be compatible and a dimension is compatible if both values are equal OR one of them is 1. Both the row AND column dimensions must pass the compatibility check — if even one dimension fails, the entire broadcasting operation fails.

In [43]:
print(r_4)
print()
print(np.add(np.array([1]), r_4))

# Adds every individual element in array by 1

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [38]:
print(r_4)
print()
print(np.add(np.array([[1]]), r_4))\
# Also adds every individual element in the array by 1

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [41]:
print(r_4)
print()
print(np.add(np.array([1,1,1,1,1]), r_4))
# np.array([1,1,1,1,1]) is a 1D array with 5 elements matching r_4's 5 columns
# since the column dimension matches, numpy can broadcast it across all 4 rows of r_4
# adding 1 to every element in r_4

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]

[[75 85 95 97 57]
 [61 70 81 30 47]
 [93 56 48 93 67]
 [21 66 25 43 47]]


In [40]:
print(r_4)
print()
print(np.add(np.array([[1], [1]]), r_4))
# This will not work since the array has 2 columns, it cannot stretch to be compatible 
# with r_4's 4 columns.

[[74 84 94 96 56]
 [60 69 80 29 46]
 [92 55 47 92 66]
 [20 65 24 42 46]]



ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

#### **How does broadcasting work?:**

Broadcasting works by stretching the dimensions of smaller arrays to match the dimensions of the larger array so the add function can be applied. With the add function, individual elements get added to each other element by element. The shape of the resulting array is determined by the largest dimension of both arrays. For broadcasting to work, every dimension must either be equal between both arrays or one of them must be 1. Both rows AND columns are checked separately — if even one dimension fails the check, the entire operation fails. For example, (2,1) cannot broadcast with (4,5) because even though the 1 column can stretch to 5, the 2 rows cannot stretch to match 4. 

The way I think of it is .add() checks every dimension individually. Rows amnd columns must match, or one has to be equal to 1. If either test for rows and columns fail, the .add() function won't work.  

## Rounding

In [19]:
# Printing r_3 to display values
print(r_3)

[[0.30490094]
 [0.42133932]]


In [11]:
# Using trunc()

print(np.trunc(r_3))

# This method returns the number with decimal places chopped off

[[0.]
 [0.]]


In [18]:
# Using fix()

print(np.fix(r_3))

# This method rounds the nearest integer toward 0
# trunc() and fix() both round toward zero by chopping off the decimal
# they produce the same result for positive numbers
# since r_3 contains floats between 0 and 1, both return 0.
# they only differ for negative numbers:
# e.g. trunc(-1.7) and fix(-1.7) both give -1, while floor(-1.7) gives -2
# if the number is already a whole number like 2, both return 2 unchanged

[[0.]
 [0.]]


In [15]:
# Using floor()

print(np.floor(r_3))

# This methhod rounds off to the nearest lower integer

[[0.]
 [0.]]


In [16]:
# Using ceil()

print(np.ceil(r_3))

# This method rounds off to nearest higher integer

[[1.]
 [1.]]


In [17]:
# Using round()

print(np.round(r_3, 2))

# This method rounds to the specifies number of deciaml places, in this case 2

[[0.3 ]
 [0.42]]


## Cumalative Operations

In [34]:
# Printing r_4 to display values
print(r_4)

[[47 54 79 57 91]
 [90 60 66 95 82]
 [57 99 39 22 56]
 [43 27 50 89 57]]


In [27]:
# Print sum of all values in r_4
print(np.sum(r_4))

1260


In [36]:
# Print the sum of elements along the 0 axis for r_4
# 0 axis moves vertically, so it moves up and down each column
# therefore, it will find sum of each column
print(np.sum(r_4, axis=0))

[237 240 234 263 286]


In [38]:
# Print the sum of elements along the 1 axis for r_4
# 1 axis moves horizontally, so it moves left to right across each row
# therefore, it will find sum of each row
print(np.sum(r_4, axis=1))

[328 393 273 266]


In [32]:
# Print the cumulative sum (rolling total) of values in r_4
print(np.cumsum(r_4))

# np.cumsum() with no axis flattens the entire array into one list
# and calculates a running total across all elements
# e.g. [10, 20, 30] after cumsum → [10, 30, 60]
# each value adds to the sum of all previous values

[  47  101  180  237  328  418  478  544  639  721  778  877  916  938
  994 1037 1064 1114 1203 1260]


In [40]:
# Print the cumulative sum (rolling total) of values along the 0  axis for r_4
print(np.cumsum(r_4, axis=0))
# axis=0 keeps the 2D shape and calculates the running total going down each column
# instead of flattening everything into one list

# row 1 stays unchanged since there is nothing before it to add to
# each subsequent row adds its values to the running total from the row above
# so you are always building on the previous result, not starting fresh each time

[[ 47  54  79  57  91]
 [137 114 145 152 173]
 [194 213 184 174 229]
 [237 240 234 263 286]]


## Grocery Problem

In [46]:
# Creating variables that represent the contents of grocery bags
# [vegatables, fruits, boxes of snacks, beverages]
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("bag1 contents:\n", bag1)
print("\nbag2 contents:\n", bag2)

bag1 contents:
 [2 3 4 0]

bag2 contents:
 [4 0 1 2]


In [50]:
# Calculate the total number of items in each bag
# Both are 1D arrays, so you can just apply sum directly

print(f"The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [52]:
# Calculate the total number of items in each category

category_totals = np.sum([bag1, bag2], axis=0)
# Since both are 1D arrays, adding them across the 0 axis calculates the total vertically, 
# moving up and down so I'll get a total for each column/category. This gives me the total of 
# each corresponding category, which I can then call by its index
print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

You are volunteering with a voter registration campaign, and you 
have been asked to oversee a squad of door-knockers. There are three people on 
your team: Ali, Ben, and Carla. Your squad went out to knock on doors each evening 
last week, Monday through Friday, and now you are assembling that data.

In [59]:
# Creating an array for the doors knocked by each team member
# Ali: 5/Monday, 4/Tuesday, 6/Wednesday, 4/Thursday, 2/Friday
knocker1 = np.array([5, 4, 5, 4, 2])
print("Ali's Progress for 5 Days:\n", knocker1)

Ali's Progress for 5 Days:
 [5 4 5 4 2]


In [65]:
# Ben: out/Monday, 5/Tuesday, 5/Wednesday, 3/Thursday, 4/Friday
knocker2 = np.array([0, 5, 5, 3, 4])
print("Ben's Progress for 5 Days:\n", knocker2)

Ben's Progress for 5 Days:
 [0 5 5 3 4]


In [63]:
# Carla: 3/Monday, 6/Tuesday, sick/Wednesday, 3/Thursday, 4/Friday
knocker3 = np.array([3, 6, 0, 3, 4])
print("Carla's Progress for 5 Days:\n", knocker3)

Carla's Progress for 5 Days:
 [3 6 0 3 4]


In [68]:
# Compile the values for all team members into a single array 
all_knocks = np.array([knocker1, knocker2, knocker3])
print(all_knocks)

[[5 4 5 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [73]:
# Calculating the total number of doors that each person knocked on for the week, and the total
# number of doors that the group collectively knocked on.

# Since I want the total of each row, I add the arrays across the 1 axis because it moves 
# horizontally left to right, calculating the elements in each row
# Each index in the resulting array is the amount for each person
weekly_knocks_per_person = np.sum(all_knocks, axis=1)
# use add() only used when adding two arrays together
print(f"Doors Knocked for the Week:\nAli:{weekly_knocks_per_person[0]}\nBen:{weekly_knocks_per_person[1]}\nCarla:{weekly_knocks_per_person[2]}")

# I want the total of the array, so I just apply sum directly
collective_knocks = np.sum(all_knocks)
print(f"\nCollective knocks:{collective_knocks}")


Doors Knocked for the Week:
Ali:20
Ben:17
Carla:16

Collective knocks:53


In [74]:
# Rolling total of estimates votes based on knock turnout for one week

# Sum all knocks by day (axis=0 adds down the columns, giving total knocks per day)
daily_knocks = np.sum(all_knocks, axis=0)

# cumsum() gives us the rolling total of doors knocked, day by day
rolling_knocks = np.cumsum(daily_knocks)

# For every 2 knocks, 1 person votes, so divide by 2
rolling_votes = rolling_knocks / 2

print(f"Estimated rolling votes by day:\n{rolling_votes}")

Estimated rolling votes by day:
[ 4.  11.5 16.5 21.5 26.5]
